name: CI
on:
- pull_request

jobs:
  sanity:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.6"]
        ansible_version: ["2.9", "2.10"]
    steps:

      - name: Check out code
        uses: actions/checkout@v1
        with:
          path: ansible_collections/community/grafana

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install ansible
        run: pip install antsibull-changelog ansible==${{ matrix.ansible_version }}

      - name: Run sanity tests
        run: ansible-test sanity --docker -v --color

      - name: Check changelog fragments syntax
        run: antsibull-changelog lint

  units:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.6"]
        ansible_version: ["2.9", "2.10"]
    steps:
      - name: Check out code
        uses: actions/checkout@v1
        with:
          path: ansible_collections/community/grafana

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install ansible
        run: pip install ansible==${{ matrix.ansible_version }}

      - name: Run unit tests
        run: ansible-test units --docker -v --color --python ${{ matrix.python_version }} --coverage

      - name: Generate coverage report.
        run: ansible-test coverage xml -v --requirements --group-by command --group-by version

      - uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: false

  integration:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        grafana_version: ["6.7.4", "7.0.6",  "7.1.3"]
        ansible_version: ["2.9", "2.10"]
        python_version: ["3.6"]
    container:
      image: python:${{ matrix.python_version }}-alpine
    services:
      grafana:
        image: grafana/grafana:${{ matrix.grafana_version }}
    steps:

      - name: Install requirements on alpine
        run: apk add bash git gcc python3-dev libc-dev libffi-dev openssl-dev

      - name: Check out code
        uses: actions/checkout@v1
        with:
          path: ansible_collections/community/grafana

      - name: Install deps
        run: pip install coverage

      - name: Install ansible
        run: pip install ansible==${{ matrix.ansible_version }}

      - name: Run integration tests on Python ${{ matrix.python_version }}
        run: ansible-test integration -v --color --retry-on-error --python ${{ matrix.python_version }} --continue-on-error --diff
